# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
 # service maps the pods into one IP address
apiVersion: v1
kind: Service
metadata:
  name: sba-kubernetes-cluster-service #name of the service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888